require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'DeliveryApp10' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-safe-area-context', :path => '../node_modules/react-native-safe-area-context'

  target 'DeliveryApp10Tests' do
    inherit! :complete
    # Pods for testing
  end

end

target 'DeliveryApp10-tvOS' do
  # Pods for DeliveryApp10-tvOS

  target 'DeliveryApp10-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
